version: '3.6'

services:
  create-react-app-service:
    container_name: create-react-app-container
    image: create-react-app-docker:1.0.0
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - type: volume
        source: mydata
        target: /home/mydata
    ports:
      - '80:80'
networks: 
  sky-net:
volumes:
  mydata: