version: '3.6'

services:
  create-react-app-service:
    container_name: create-react-app-container
    image: create-react-app-docker:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true